/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#353437",
        "on-tertiary-fixed": "#370e00",
        "surface-bright": "#39393b",
        "on-secondary-fixed-variant": "#344088",
        "tertiary-fixed-dim": "#ffb599",
        "on-primary": "#001d93",
        "primary-fixed-dim": "#bbc3ff",
        "outline": "#8e8fa2",
        "on-secondary-fixed": "#010f5c",
        "inverse-on-surface": "#313032",
        "surface-container-lowest": "#0e0e10",
        "secondary": "#bbc3ff",
        "error": "#ffb4ab",
        "on-tertiary": "#5a1c00",
        "on-tertiary-container": "#ffeee8",
        "on-secondary-container": "#a9b4ff",
        "on-error": "#690005",
        "outline-variant": "#444656",
        "on-primary-fixed-variant": "#002ccd",
        "surface-container": "#201f22",
        "surface-tint": "#bbc3ff",
        "surface-dim": "#131315",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#7f2b00",
        "on-surface-variant": "#c5c5d9",
        "surface-container-low": "#1c1b1e",
        "background": "#131315",
        "tertiary-fixed": "#ffdbce",
        "on-primary-fixed": "#000f5d",
        "on-background": "#e5e1e4",
        "secondary-fixed": "#dee0ff",
        "primary-fixed": "#dee0ff",
        "tertiary-container": "#c04500",
        "tertiary": "#ffb599",
        "on-primary-container": "#f1f0ff",
        "primary-container": "#3d5afe",
        "surface": "#131315",
        "inverse-surface": "#e5e1e4",
        "primary": "#bbc3ff",
        "on-secondary": "#1c2971",
        "surface-container-high": "#2a2a2c",
        "secondary-container": "#37438b",
        "inverse-primary": "#2848ee",
        "surface-container-highest": "#353437",
        "secondary-fixed-dim": "#bbc3ff",
        "on-surface": "#e5e1e4",
        "on-error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem", 
        "lg": "0.25rem", 
        "xl": "0.5rem", 
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
